name: vnc-vm

on:
  workflow_dispatch:

env:
  ATTIC_CACHE_NAME: ${{ secrets.ATTIC_CACHE_NAME }}
  ATTIC_CACHE_URL: ${{ secrets.ATTIC_CACHE_URL }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

jobs:
  vnc-vm:
    runs-on: macos-latest
    timeout-minutes: 300 # 5 hours

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Configure Attic cache
        run: |
          nix run nixpkgs#attic-client -- login \
            "${{ env.ATTIC_CACHE_NAME }}" "${{ env.ATTIC_CACHE_URL }}" "${{ env.ATTIC_TOKEN }}"
          nix run nixpkgs#attic-client -- use darwinix

      - name: Install cloudflared
        run: |
          brew install cloudflare/cloudflare/cloudflared

      - name: Start Cloudflare Quick Tunnel for VNC
        run: |
          echo "Starting Cloudflare Quick Tunnel..."
          cloudflared tunnel --url tcp://localhost:5900 > tunnel.log 2>&1 &

          # Wait for tunnel to establish
          echo "Waiting for tunnel to establish..."
          sleep 15

          # Extract and display the tunnel URL
          echo "=========================================="
          echo "VNC CONNECTION INFORMATION:"
          echo "=========================================="
          TUNNEL_URL=$(grep -o 'https://[^[:space:]]*\.trycloudflare\.com' tunnel.log | head -1)
          echo "Tunnel URL: $TUNNEL_URL"
          echo ""
          echo "To connect via VNC client:"
          echo "1. Copy the hostname from the URL above (without https://)"
          echo "2. Use port 5900 or as specified by your VNC client"
          echo "3. No password required"
          echo "=========================================="
          echo ""
          echo "Tunnel will remain active for 5 hours or until workflow is cancelled"

      - name: Run VM with VNC
        env:
          GRAPHICS: 0
          NETWORK: 1
        run: |
          echo "Starting NixOS VM with VNC enabled..."
          echo "VM will run for up to 5 hours or until manually stopped"
          nix run path:.#nixos -- -vnc :0
